// ═══════════════════════════════════════════════════
// KlasWerk — Config Reader
// ───────────────────────────────────────────────────
// Reads window.KLASWERK_CONFIG (injected by public/config.js),
// validates required fields, applies brand CSS variables,
// and exports a typed config object for use throughout the app.
// ═══════════════════════════════════════════════════

import type { KlasWerkConfig } from '@/types'

// Extend window so TypeScript knows about our global
declare global {
  interface Window {
    KLASWERK_CONFIG: KlasWerkConfig
  }
}

// ── Validation ───────────────────────────────────────────────────────────────
function validateConfig(cfg: Partial<KlasWerkConfig>): KlasWerkConfig {
  const missing: string[] = []

  if (!cfg.app?.name)          missing.push('app.name')
  if (!cfg.supabase?.url)      missing.push('supabase.url')
  if (!cfg.supabase?.anonKey)  missing.push('supabase.anonKey')

  if (missing.length > 0) {
    console.error(
      '[KlasWerk] Missing required config fields:',
      missing.join(', '),
      '\nMake sure public/config.js is present and has been generated by the Setup Wizard.'
    )
  }

  return cfg as KlasWerkConfig
}

// ── Brand CSS variable injection ─────────────────────────────────────────────
// Called once on startup — maps config.brand colours to CSS custom properties
// so Tailwind kw-* colours and any raw var(--kw-*) references work correctly.
function applyBrandTokens(brand: KlasWerkConfig['brand']): void {
  const root = document.documentElement

  // Derive a simple dark/light scale from the primary colour
  root.style.setProperty('--kw-primary',    brand.primary)
  root.style.setProperty('--kw-primary-dk', brand.secondary)
  root.style.setProperty('--kw-primary-lt', lighten(brand.primary, 20))
  root.style.setProperty('--kw-primary-glow', hexToRgba(brand.primary, 0.12))

  // Background scale — use the client's background/surface values
  root.style.setProperty('--kw-black',     darken(brand.background, 10))
  root.style.setProperty('--kw-dark',      brand.background)
  root.style.setProperty('--kw-surface',   brand.surface)
  root.style.setProperty('--kw-panel',     lighten(brand.surface, 5))
  root.style.setProperty('--kw-border',    lighten(brand.surface, 10))
  root.style.setProperty('--kw-border-lt', lighten(brand.surface, 18))

  // Text — fixed, warm palette
  root.style.setProperty('--kw-cream',   '#f0e6ce')
  root.style.setProperty('--kw-muted',   '#7a6d58')
  root.style.setProperty('--kw-success', '#4caf7a')
  root.style.setProperty('--kw-danger',  '#c94c4c')

  // Favicon — if client has supplied one
  if (brand.faviconUrl) {
    const favicon = document.getElementById('kw-favicon') as HTMLLinkElement | null
    if (favicon) favicon.href = brand.faviconUrl
  }

  // Page title
  // (will be set again by the router per-page, this is the fallback)
}

// ── Colour utilities ─────────────────────────────────────────────────────────
function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return `rgba(${r},${g},${b},${alpha})`
}

function lighten(hex: string, amount: number): string {
  return adjustBrightness(hex, amount)
}

function darken(hex: string, amount: number): string {
  return adjustBrightness(hex, -amount)
}

function adjustBrightness(hex: string, amount: number): string {
  // Guard against malformed hex
  if (!hex || hex.length < 7) return hex
  const r = Math.max(0, Math.min(255, parseInt(hex.slice(1, 3), 16) + amount))
  const g = Math.max(0, Math.min(255, parseInt(hex.slice(3, 5), 16) + amount))
  const b = Math.max(0, Math.min(255, parseInt(hex.slice(5, 7), 16) + amount))
  return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`
}

// ── Bootstrap ────────────────────────────────────────────────────────────────
function loadConfig(): KlasWerkConfig {
  const raw = window.KLASWERK_CONFIG

  if (!raw) {
    console.error(
      '[KlasWerk] window.KLASWERK_CONFIG is not defined.',
      'Make sure public/config.js is loaded before the React bundle (check index.html).'
    )
    // Return a minimal safe fallback so the app at least renders an error state
    return {
      app: { name: 'KlasWerk', clientCode: 'error', url: '/', supportEmail: '', currency: 'ZAR', language: 'en' },
      supabase: { url: '', anonKey: '', serviceKey: '' },
      r2: { endpoint: '', bucket: '', accessKey: '', secretKey: '', publicUrl: '' },
      payfast: { merchantId: '', merchantKey: '', passphrase: '', testMode: true, notifyUrl: '', returnUrl: '/', cancelUrl: '/' },
      whereby: { embedUrl: '', apiKey: '' },
      features: { liveSessions: false, quizzes: false, certificates: false, payments: false, analytics: false },
      brand: { primary: '#c9943c', secondary: '#7a5815', background: '#110e09', surface: '#1a1610', logoUrl: '', faviconUrl: '' },
    }
  }

  const config = validateConfig(raw)
  applyBrandTokens(config.brand)

  return config
}

// ── Exports ──────────────────────────────────────────────────────────────────
export const config = loadConfig()

// Convenience named exports for the most-used sections
export const appConfig      = config.app
export const supabaseConfig = config.supabase
export const payfastConfig  = config.payfast
export const wherebyConfig  = config.whereby
export const r2Config       = config.r2
export const features       = config.features
export const brand          = config.brand

export default config
